### ISSUE TITLE
misplaced print statement in linearRidge.R

### ISSUE THREAD

**Issue by jtanevski** [SteffenMoritz/ridge#17]
Since the last commit (548f48de31b8757571d83e6f2eb50b1d9a8a560f), on line 47 in linearRidge.R there is a misplaced `print(m)`. This is probably a leftover from a debug session that causes unwanted clutter in the output when using `ridge`.

**Comment by SteffenMoritz** [comment]
Jovan, thank you so much for opening an issue. 

`This is probably a leftover from a debug session that causes unwanted clutter in the output when using ridge.`

Totally true, I'll upload a fixed version this week.

**Comment by SteffenMoritz** [comment]
New version is on it's way to CRAN :)
