### ISSUE TITLE
linux conda install ridge failed

### ISSUE THREAD

**Issue by shufanzhang** [SteffenMoritz/ridge#19]
1. I try to use ‘conda install -c r r-ridge’， but it keep Solving environment without stopped
2. I try to install ridge with https://cran.r-project.org/src/contrib/ridge_3.2.tar.gz，i apt install gcc and GSL， but it still can not install.
information is as follows:

> install.packages("/home/shufan/software/oncoPredict/ridge_3.2.tar.gz",repos = NULL,type = "source")

* installing *source* package ‘ridge’ ...
** package ‘ridge’ successfully unpacked and MD5 sums checked
** using staged installation
/home/xxx/anaconda3/envs/drug/lib/R/bin/config: 1: eval: make: not found
/home/xxx/anaconda3/envs/drug/lib/R/bin/config: 1: eval: make: not found
/home/xxx/anaconda3/envs/drug/lib/R/bin/config: 1: eval: make: not found
/home/xxx/anaconda3/envs/drug/lib/R/bin/config: 1: eval: make: not found
/home/xxx/anaconda3/envs/drug/lib/R/bin/config: 1: eval: make: not found

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for gsl-config... /usr/bin/gsl-config
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gsl/gsl_version.h... yes
configure: creating ./config.status
config.status: creating R/linearRidgeGenotypes.R
config.status: creating R/linearRidgeGenotypesPredict.R
config.status: creating R/logisticRidgeGenotypes.R
config.status: creating R/logisticRidgeGenotypesPredict.R
config.status: creating src/Makevars
config.status: creating src/config.h
config.status: src/config.h is unchanged
** libs
sh: 1: make: not found
Warning in system(cmd) : 调用命令时发生了错误
ERROR: compilation failed for package ‘ridge’

**Comment by SteffenMoritz** [comment]
Don't think this is an issue with the package itself but rather about getting the requirements for the package right.

I am not using conda myself, but let me try to help you. Here are some things that could work:

Usually when you get an error like "make not found" you need to install RTools to be able to install the package from source.
(for windows)
Or run `sudo apt-get install make` to install make on linux.

Also see https://stackoverflow.com/questions/53279685/r-make-not-found-when-installing-a-r-package-from-local-tar-gz

**Comment by SteffenMoritz** [comment]
Closed as it is not really an issue with the package.
I hope my comment helps to get the requirements right.
(otherwise feel free to reopen the issue)

**Comment by shufanzhang** [comment]
Thank you for your respond and I install it on my win10 successful. Even if I run sudo apt-get install make, I still can't install it successfully in the linux conda environment, I think it may be related to my linux environment or conda.

**Comment by SteffenMoritz** [comment]
Is the error message after you installed sudo apt-get install make still the same?

**Comment by shufanzhang** [comment]
Yes, still the same.
In fact, R packages are usually well installed in a conda environment with ‘conda install -c bioconda -c conda-forge package_name_to_install’. But ridge only has ‘conda install -c r r-ridge’,  ‘-c r’ often causes various conflicts to cause the installation to fail.
If I install successfully, I will leave a message later.

**Comment by orange511** [comment]
I encountered the same error in my Conda environment on a Linux HPC. After some troubleshooting, I successfully installed the r-ridge package using the following command: `mamba install r-ridge --freeze-installed`.
This resolved the issue for me. Thanks to everyone for the helpful suggestions!
