### ISSUE TITLE
Error in numeric(nPCs) : invalid 'length' argument

### ISSUE THREAD

**Issue by badbye** [SteffenMoritz/ridge#2]
Here in `https://github.com/cran/ridge/blob/master/R/linearRidge.R#L96`,
```
nPCs <- which.max(propVar[propVar < 90]) + 1
```
what if all the elements in `propVar` are greater than 90? It will throw an error, which is the title of this issue.

**Comment by SteffenMoritz** [comment]
THX for your bug report. I tried to fix it.
Would you mind making a install from Github to see if the error disappeared?

**Comment by badbye** [comment]
A similar error: 
```
Error in if (which.max(propVar[propVar < 90]) > 0) { :
  argument is of length zero
```

**Comment by badbye** [comment]
Hi, I do not mind share my data and code: 
```
mydata = read.csv('https://gist.githubusercontent.com/badbye/c4be83a28f4f6f10e2e067189f67d834/raw/a42b4bc7e4b3c570267902cd9e140a33343bfe8e/test%2520the%2520%2560ridge%2560%2520package')
m = linearRidge(y ~ ., data = mydata)
```
You can use it to test your code. I know this dataset do not need to use ridge regression. It is still better to make this package more robust. Hope you agree with me.

**Comment by SteffenMoritz** [comment]
Took me some time (cause I had multiple other things to do...).
But I think I fixed the issue.

Thanks again badbye for reporting the bug !! :-)
